name: Flutter Web CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Web Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.16.9' # the Flutter version

    - name: Install Dependencies
      run: flutter pub get

    - name: Build Web
      run: flutter build web --release --base-href=/bluish-sky/

    - name: Upload Web Build Files
      uses: actions/upload-artifact@v2
      with:
        name: web-release
        path: build/web

  deploy:
    name: Deploy Web Build
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Download Web Release
      uses: actions/download-artifact@v2
      with:
        name: web-release
        path: web

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web